### ISSUE TITLE
Excel file example for noobs

### ISSUE THREAD

**Issue by 9il** [kaleidicassociates/excel-d#21]
Hi Atila,

Could you please add a simple example for of an excel file witch use XLL function call with matrix I/O?

**Comment by Laeeth** [comment]
I think most likely it works with arrays of arrays currently and maybe not yet a true matrix and that adding a true matrix was something to add, but not implemented yet - and maybe you can help me + Atila add it.

**Comment by 9il** [comment]
Array of arrays are Ok for now. The problem is Excel part :/

**Comment by 9il** [comment]
I have tried Excel file from excel-d master (it is the same as I have done myself). It does not work for me at all. I have loaded excel-d add-in, it is active. But there are no functions from the add-in. It is so weird...

**Comment by 9il** [comment]
I am going to update Win 8 PC to Win 10 and change default system language to English (my Win 8 does not allow it). Hope this will fix the problem.
