### ISSUE TITLE
ExcelD hangs up on a big table

### ISSUE THREAD

**Issue by 9il** [kaleidicassociates/excel-d#22]
How to reproduce: pass to the FuncBob in the example a big table (30 columns × 4000 rows)

**Comment by 9il** [comment]
This issue is a blocker

**Comment by 9il** [comment]
If it passes for the first time, try to recalculate table few times.

**Comment by atilaneves** [comment]
Reproducible with a function from the example: `=FuncAllLengths(B1:AL4000)` on A1 will crash Excel.
