### ISSUE TITLE
[Blocker] No universal conversion to strings

### ISSUE THREAD

**Issue by 9il** [kaleidicassociates/excel-d#23]
##### Motivation
A table contains dates, numbers, and strings (headers, and NaNs).
So it should be convertible to a universal type like `string[][]` or `Variant[][]`.

##### How to reproduce
Change the function in the example to `FuncBob`

##### Note
Text cell formatting does not help.

**Comment by 9il** [comment]
BTW, `Date` support for an excel-d algebraic type would be very nice to have.

**Comment by atilaneves** [comment]
There's a type called `Any`.
It's a variant that supports exactly the same types as Excel does. Just declare your function to take `Any`, `Any[]` or `Any[][]`. Unfortunately that means knowing how `Any` works and manually inspecting the type (it contains an `XLOPER12` inside.

**Comment by atilaneves** [comment]
Check the date functions in `xlld.xlf` - Excel uses `double` as a date type. There's no automatic conversion right now though - I agree it'd be nice to automatically convert to/from `std.datetime.DateTime`.
