### ISSUE TITLE
[blocker] Excel-D does not work with two table in some cases.

### ISSUE THREAD

**Issue by 9il** [kaleidicassociates/excel-d#25]
Atila, please open the file I sent before. 
`=M2DTest4(swapUS_table, ANY_EMPTY_TABLE)`
```d
Any[][] M2DTest4(Any[][] a, Any[][] b) nothrow {
    return a;
}
```
64 bit excel, recent dmd,.
Two arguments is matter.
swapUS_table is matter.

**Comment by atilaneves** [comment]
I can reproduce this by assigning `=M2DTest4(c1:e2, c4:e5)` to a six cell matrix, having `c1:e2` be 1, 2, 3, 4, 5, 6, and `c4:e6` empty. Then I change 2 to `foo` and Excel crashes.
