### ISSUE TITLE
No documentation about generation of def file

### ISSUE THREAD

**Issue by ArjanKn** [kaleidicassociates/excel-d#32]
The mandatory addin.def file is nowhere documented or mentioned.

**Comment by atilaneves** [comment]
The `.def` file doesn't have to be called `addin.def`, and it only necessary for the generation of the XLL. The example has a working `dub.sdl` file that generates the `.def` and uses it when linking.

**Comment by ArjanKn** [comment]
Yes the name is not the point, The point is that particularity of the `def` file is not mentioned anywhere and someone not aware of windows dll and exports has to scrutinize the example `sdl` file to find out.

**Comment by atilaneves** [comment]
I see. I'll change README.md.
