### ISSUE TITLE
asynchronous UDF functionality  - UDAs, wrapping and registration

### ISSUE THREAD

**Issue by Laeeth** [kaleidicassociates/excel-d#4]
https://msdn.microsoft.com/en-us/library/office/ff796219(v=office.14).aspx

**Comment by Laeeth** [comment]
in particular this is useful for example for long-running get/put operations.  we don't want to block excel whilst the data access operation is running.  much better to return immediately and update a status when remote server returns it.

also useful for long-running calculations

**Comment by atilaneves** [comment]
Duplicate of #35
