### ISSUE TITLE
What command to issue for compiling?

### ISSUE THREAD

**Issue by mnar53** [kaleidicassociates/excel-d#62]
Sorry for the silly question, but I've just installed D (dmd and ldc) for the first time. My Excel is 64 bit, and I copied in the example folder the right xlcall32 lib. But the command  'dub build --arch=x86_64' , from the example folder, ends with lot of errors, related to function xlld.wrap.wrap.stringAutoFreeOper not callable

1) should i use dmd or ldc?
2) should i first issue a command in the root folder? which?
3) which is the correct command from the example folder ?

**Comment by atilaneves** [comment]
Sorry, a nogc version update broke excel-d. To build the command after the fix, just use `dub build --arch=x86_64` in the example directory.
