### ISSUE TITLE
Need a tag for the dlang project tester

### ISSUE THREAD

**Issue by Basile-z** [kaleidicassociates/excel-d#63]
Maybe the one that was put 16 hours ago was pushed before a local pull of @atilaneves changes ?
Anyway it would be nice to have a new one on caf2295ea5cf9968e95b8cd0121a191a87631528.

**Comment by atilaneves** [comment]
What's wrong with the `v0.3.10` tag?

**Comment by wilzbach** [comment]
It doesn't build as the commit mentioned isn't included in it. See e.g. https://buildkite.com/dlang/dub/builds/410

**Comment by atilaneves** [comment]
`v0.3.10` points to that exact same commit. However, I see that it doesn't build with nightly so I tagged a new one.

**Comment by wilzbach** [comment]
Works now. Thanks!
